module.exports = {
    ENTER_REGION: "ENTER_REGION",
    LEAVE_REGION: "LEAVE_REGION",
    PLAYER_MOVE: "PLAYER_MOVE",
    PLAYER_JOIN: "PLAYER_JOIN",
    PLAYER_UPDATE: "PLAYER_UPDATE",
    TILE_UPDATE: "TILE_UPDATE"
};




